version : '3.8'

services:
  web:
    build: ./services/api

    expose:
      - 8000

    restart: 'always'

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`api.algoscale.com`)"
   

  traefik:
    image: traefik:v2.3
    ports:
      - "80:80"
      - "443:443"
     
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./:/etc/traefik"
      - "/certificates:/certificates/acme.json"
