[entryPoints]
  [entryPoints.web]
    address = ":80"

[api]
    dashboard = true
    insecure = true

[log]
    level = "DEBUG"

[accessLog]

[providers]
  [providers.docker]
    exposedByDefault = false